CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    total NUMERIC(38,2) NOT NULL,
    discount NUMERIC(38,2),
    freight NUMERIC(38,2),
    address TEXT,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    price_snapshot NUMERIC(38,2) NOT NULL
);

ALTER TABLE order_items
    ADD CONSTRAINT fk_orderitems_order
        FOREIGN KEY (order_id) REFERENCES orders(id);

ALTER TABLE order_items
    ADD CONSTRAINT fk_orderitems_product
        FOREIGN KEY (product_id) REFERENCES products(id);