CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode VARCHAR(255),
    name VARCHAR(255),
    price NUMERIC(38,2) NOT NULL,
    category_id BIGINT NOT NULL,
    user_id VARCHAR(255)
);

ALTER TABLE products
    ADD CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories(id);

ALTER TABLE products
    ADD CONSTRAINT fk_products_user
        FOREIGN KEY (user_id) REFERENCES users(id);