CREATE TABLE inventories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT UNIQUE,
    quantity INT NOT NULL,
    min_level INT NOT NULL
);

ALTER TABLE inventories
    ADD CONSTRAINT fk_inventories_product
        FOREIGN KEY (product_id) REFERENCES products(id);
