CREATE TYPE inventory_tx_type AS ENUM ('ENTRY', 'EXIT', 'ADJUSTMENT', 'RETURN');

CREATE TABLE inventory_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type inventory_tx_type NOT NULL,
    reason VARCHAR(255),
    user_id VARCHAR(255)
);

ALTER TABLE inventory_transactions
    ADD CONSTRAINT fk_inventorytx_inventory
        FOREIGN KEY (inventory_id)
        REFERENCES inventories(id);

ALTER TABLE inventory_transactions
    ADD CONSTRAINT fk_inventorytx_user
        FOREIGN KEY (user_id)
        REFERENCES users(id);
