CREATE TYPE promotion_type AS ENUM ('FIXED', 'PERCENTAGE');

CREATE TABLE promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type promotion_type NOT NULL,
    amount NUMERIC(38,2) NOT NULL,
    start_at TIMESTAMP(6),
    end_at TIMESTAMP(6),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    category_id BIGINT,
    product_id BIGINT
);

ALTER TABLE promotions
    ADD CONSTRAINT fk_promotions_category
        FOREIGN KEY (category_id) REFERENCES categories(id);

ALTER TABLE promotions
    ADD CONSTRAINT fk_promotions_product
        FOREIGN KEY (product_id) REFERENCES products(id);


CREATE TABLE coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    start_at TIMESTAMP(6),
    end_at TIMESTAMP(6),
    usage_limit INT,
    used_count INT,
    promotion_id BIGINT NOT NULL
);

ALTER TABLE coupons
    ADD CONSTRAINT fk_coupons_promotion
        FOREIGN KEY (promotion_id) REFERENCES promotions(id);


CREATE TABLE coupon_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id BIGINT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    used_at TIMESTAMP(6)
);

ALTER TABLE coupon_usages
    ADD CONSTRAINT fk_couponusages_coupon
        FOREIGN KEY (coupon_id) REFERENCES coupons(id);

ALTER TABLE coupon_usages
    ADD CONSTRAINT fk_couponusages_user
        FOREIGN KEY (user_id) REFERENCES users(id);
