CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_amount NUMERIC(38,2),
    updated_at TIMESTAMP(6),
    user_id VARCHAR(255) NOT NULL UNIQUE
);

ALTER TABLE carts
    ADD CONSTRAINT fk_carts_user
        FOREIGN KEY (user_id) REFERENCES users(id);


CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_snapshot NUMERIC(38,2) NOT NULL,
    quantity INT NOT NULL,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL
);

ALTER TABLE cart_items
    ADD CONSTRAINT fk_cartitems_cart
        FOREIGN KEY (cart_id) REFERENCES carts(id);

ALTER TABLE cart_items
    ADD CONSTRAINT fk_cartitems_product
        FOREIGN KEY (product_id) REFERENCES products(id);
