CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(255) NOT NULL,
    changed_by VARCHAR(255) NOT NULL,
    entity_name VARCHAR(255) NOT NULL,
    entity_id BIGINT NOT NULL,
    changed_at TIMESTAMP(6) NOT NULL,
    old_value TEXT,
    new_value TEXT
);


